In [1]:
import os 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
avazu_data_path = os.path.join(os.getcwd(), '../data/raw/avazu', 'train.gz')
avazu_data = pd.read_csv(avazu_data_path, compression='gzip')
avazu_data.head()

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1.000009e+18,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15706,320,50,1722,0,35,-1,79
1,1.000017e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
2,1.000037e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
3,1.000064e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15706,320,50,1722,0,35,100084,79
4,1.000068e+19,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,7801e8d9,...,1,0,18993,320,50,2161,0,35,-1,157

In [3]:
avazu_data.shape

(40428967, 24)

In [4]:
avazu_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40428967 entries, 0 to 40428966
Data columns (total 24 columns):
 #   Column            Dtype
---  ------            -----
 0   id                float64
 1   click             int64
 2   hour              int64
 3   C1                int64
 4   banner_pos        int64
 5   site_id           object
 6   site_domain       object
 7   site_category     object
 8   app_id            object
 9   app_domain        object
 10  app_category      object
 11  device_id         object
 12  device_ip         object
 13  device_model      object
 14  device_type       int64
 15  device_conn_type  int64
 16  C14               int64
 17  C15               int64
 18  C16               int64
 19  C17               int64
 20  C18               int64
 21  C19               int64
 22  C20               int64
 23  C21               int64
dtypes: float64(1), int64(14), object(9)
memory usage: 7.2+ GB

In [5]:
pd.set_option('display.float_format', '{:.2f}'.format)
avazu_data.describe(percentiles=[.01, .05, .1, .25, .5, .75, .9, .95, .99])

,id,click,hour,C1,banner_pos,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
count,40428967.00,40428967.00,40428967.00,40428967.00,40428967.00,40428967.00,40428967.00,40428967.00,40428967.00,40428967.00,40428967.00,40428967.00,40428967.00,40428967.00,40428967.00
mean,9223017109830735872.00,0.17,14102558.25,1004.97,0.29,1.02,0.33,18841.81,318.88,60.10,2112.60,1.43,227.14,53216.85,83.38
std,5325443366632439808.00,0.38,296.68,1.09,0.51,0.53,0.85,4959.46,21.27,47.30,609.41,1.33,351.02,49956.82,70.29
min,521159373627.00,0.00,14102100.00,1001.00,0.00,0.00,0.00,375.00,120.00,20.00,112.00,0.00,33.00,-1.00,1.00
1%,184541128679537696.00,0.00,14102102.00,1002.00,0.00,0.00,0.00,456.00,300.00,50.00,122.00,0.00,33.00,-1.00,15.00
5%,921895806156952064.00,0.00,14102109.00,1002.00,0.00,0.00,0.00,6392.00,300.00,50.00,547.00,0.00,35.00,-1.00,23.00
10%,1843934416309410048.00,0.00,14102122.00,1005.00,0.00,1.00,0.00,15699.00,320.00,50.00,1722.00,0.00,35.00,-1.00,23.00
25%,4611180815200744448.00,0.00,14102304.00,1005.00,0.00,1.00,0.00,16920.00,320.00,50.00,1863.00,0.00,35.00,-1.00,23.00
50%,9223223753932312576.00,0.00,14102602.00,1005.00,0.00,1.00,0.00,20346.00,320.00,50.00,2323.00,2.00,39.00,100048.00,61.00
75%,13835611070681530368.00,0.00,14102814.00,1005.00,1.00,1.00,0.00,21894.00,320.00,50.00,2526.00,3.00,171.00,100093.00,101.00
90%,16603061182361944064.00,1.00,14103001.00,1005.00,1.00,1.00,2.00,23144.00,320.00,50.00,2665.00,3.00,803.00,100173.00,221.00
95%,17525171800011849728.00,1.00,14103012.00,1005.00,1.00,1.00,3.00,23561.00,320.00,50.00,2691.00,3.00,1063.00,100190.00,221.00
99%,18262535905598017536.00,1.00,14103020.00,1010.00,1.00,4.00,3.00,23866.00,320.00,250.00,2736.00,3.00,1327.00,100206.00,229.00
max,18446743972517787648.00,1.00,14103023.00,1012.00,7.00,5.00,5.00,24052.00,1024.00,1024.00,2758.00,3.00,1959.00,100248.00,255.00

In [6]:
avazu_data.isnull().sum()

id                  0
click               0
hour                0
C1                  0
banner_pos          0
site_id             0
site_domain         0
site_category       0
app_id              0
app_domain          0
app_category        0
device_id           0
device_ip           0
device_model        0
device_type         0
device_conn_type    0
C14                 0
C15                 0
C16                 0
C17                 0
C18                 0
C19                 0
C20                 0
C21                 0
dtype: int64